- alias: "Startup Notification"
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.pushbullet
    data:
      title: "Alert"
      message: "Home Assistant restarted"
- alias: "Away Thermostat"
  trigger:
    - platform: numeric_state
      entity_id: !secret travel_sensor_id_3
      above: '15'
    - platform: numeric_state
      entity_id: !secret travel_sensor_id_4
      above: '15'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: !secret travel_sensor_id_3
      above: '15'
    - condition: numeric_state
      entity_id: !secret travel_sensor_id_4
      above: '15'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.home
        away_mode: true
    - service: notify.pushbullet
      data:
        title: "Alert"
        message: "Thermostat set to Away"
    - service: automation.turn_on
      data:
        entity_id: automation.home_thermostat
    - service: automation.turn_off
      data:
        entity_id: automation.away_thermostat        
- alias: "Home Thermostat"
  initial_state: False
  trigger:
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.home
        away_mode: false
    - service: notify.pushbullet
      data:
        title: "Alert"
        message: "Thermostat set home"
    - service: automation.turn_on
      data:
        entity_id: automation.away_thermostat
    - service: automation.turn_off
      data:
        entity_id: automation.home_thermostat
- alias: "Daily Restart"
  trigger:
    platform: time
    hours: 1
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.restart
