- alias: "Startup Notification"
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.pushbullet
    data:
      title: "Alert"
      message: "Home Assistant restarted"
- alias: "Daily Restart"
  trigger:
    platform: time
    hours: 1
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.restart
