homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 193
  unit_system: imperial
  time_zone: America/Chicago

# Enables the frontend
frontend:

http:
  # Login password
   api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Configuration
config:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: pi_hole
  - platform: moon
#  - platform: darksky
#    api_key: !secret darksky_api_key
#    monitored_conditions:
#      - summary
#      - icon
#      - nearest_storm_distance
#      - nearest_storm_bearing
#      - precip_type
#      - precip_intensity
#     - precip_probability
#      - temperature
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_bearing
#      - cloud_cover
#      - humidity
#      - pressure
#      - visibility
#      - ozone
#      - minutely_summary
#      - hourly_summary
#      - daily_summary
#      - temperature_max
#      - temperature_min
#      - apparent_temperature_max
#      - apparent_temperature_min
#      - precip_intensity_max


# Text to speech
tts:
  platform: google

# Thermostat
ecobee:
  api_key: !secret ecobee_api_key

zone: !include zones.yaml

#device_tracker: !include device_tracker.yaml
#device_tracker:
# Sends notifications
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

automation: !include automations.yaml
group: !include groups.yaml

#android_ip_webcam:
#  - host: 192.168.1.4
#    name: TestCam
