homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 193
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Enables the frontend
frontend:

http:
  # Login password
   api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: google_travel_time
    name: !secret travel_sensor_1
    api_key: !secret google_distance_api_key
    origin: !secret device_1
    destination: !secret zone_2_id
  - platform: google_travel_time
    name: !secret travel_sensor_2
    api_key: !secret google_distance_api_key
    origin: !secret device_2
    destination: !secret zone_3_id
  - platform: google_travel_time
    name: !secret travel_sensor_3
    api_key: !secret google_distance_api_key
    origin: !secret device_1
    destination: zone.home
  - platform: google_travel_time
    name: !secret travel_sensor_4
    api_key: !secret google_distance_api_key
    origin: !secret device_2
    destination: zone.home
  - platform: google_travel_time
    name: !secret travel_sensor_5
    api_key: !secret google_distance_api_key
    origin: !secret device_1
    destination: !secret device_2


# Text to speech
tts:
  platform: google

# Thermostat
ecobee:
  api_key: !secret ecobee_api_key

# Location tracking broker
mqtt:
  broker: !secret mosquitto_broker
  port: !secret mosquitto_port
  client_id: !secret mosquitto_client_id
  username: !secret mosquitto_username
  password: !secret mosquitto_password

zone: !include zones.yaml

device_tracker: !include device_tracker.yaml

# Sends notifications
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

automation:
  - alias: "Startup Notification"
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      service: notify.pushbullet
      data:
        title: "Alert"
        message: "Home Assistant restarted"
  - alias: "Away Thermostat"
    trigger:
      - platform: numeric_state
        entity_id: !secret travel_sensor_id_3
        above: '15'
      - platform: numeric_state
        entity_id: !secret travel_sensor_id_4
        above: '15'
    condition:
      condition: and
      conditions:
      - condition: numeric_state
        entity_id: !secret travel_sensor_id_3
        above: '15'
      - condition: numeric_state
        entity_id: !secret travel_sensor_id_4
        above: '15'
    action:
      - service: climate.set_away_mode
        data:
          away_mode: true
      - service: notify.pushbullet
        data:
          title: "Alert"
          message: "Thermostat set to Away"
  - alias: "Home Thermostat"
    trigger:
      - platform: numeric_state
        entity_id: !secret travel_sensor_id_3
        below: '15'
      - platform: numeric_state
        entity_id: !secret travel_sensor_id_4
        below: '15'
    condition:
      condition: or
      conditions:
      - condition: numeric_state
        entity_id: !secret travel_sensor_id_3
        below: '15'
      - condition: numeric_state
        entity_id: !secret travel_sensor_id_4
        below: '15'
    action:
      - service: climate.set_away_mode
        data:
          away_mode: false
      - service: notify.pushbullet
        data:
          title: "Alert"
          message: "Thermostat set to Home"