- platform: yr

#- platform: google_travel_time
#  name: !secret travel_sensor_1
#  api_key: !secret google_distance_api_key
#  origin: !secret device_1
#  destination: !secret zone_2_id

- platform: google_travel_time
  name: !secret travel_sensor_2
  api_key: !secret google_distance_api_key
  origin: !secret device_2
  destination: !secret zone_3_id

- platform: google_travel_time
  name: !secret travel_sensor_3
  api_key: !secret google_distance_api_key
  origin: !secret device_1
  destination: !secret zone_1_id

- platform: google_travel_time
  name: !secret travel_sensor_4
  api_key: !secret google_distance_api_key
  origin: !secret device_2
  destination: !secret zone_1_id

#- platform: google_travel_time
#  name: !secret travel_sensor_5
#  api_key: !secret google_distance_api_key
#  origin: !secret device_1
#  destination: !secret device_2